cs3240_f15_team14/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^mainpage/', include('mainpage.urls')),
    url(r'^myapplication/', include('myapplication.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^uploader/',include('uploader.urls')),
    url(r'^siteadmin/', include('siteadmin.urls')),
    url(r'^messages/', include('postman.urls', namespace='postman', app_name='postman')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dev/cs3240_f15_team14/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^myapplication/', include('myapplication.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^uploader/',include('uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

postman/urls.py
"""
If the default usage of the views suits you, simply use a line like
this one in your root URLconf to set up the default URLs::

    (r'^messages/', include('postman.urls', namespace='postman', app_name='postman')),

Otherwise you may customize the behavior by passing extra parameters.

Recipients Max
--------------
Views supporting the parameter are: ``WriteView``, ``ReplyView``.
Example::
    ...View.as_view(max=3), name='write'),
See also the ``POSTMAN_DISALLOW_MULTIRECIPIENTS`` setting

User filter
-----------
Views supporting a user filter are: ``WriteView``, ``ReplyView``.
Example::
    def my_user_filter(user):
        if user.get_profile().is_absent:
            return "is away"
        return None
    ...
    ...View.as_view(user_filter=my_user_filter), name='write'),

function interface:
In: a User instance
Out: None, False, '', 'a reason', or ValidationError

Exchange filter
---------------
Views supporting an exchange filter are: ``WriteView``, ``ReplyView``.
Example::
    def my_exchange_filter(sender, recipient, recipients_list):
        if recipient.relationships.exists(sender, RelationshipStatus.objects.blocking()):
            return "has blacklisted you"
        return None
    ...
    ...View.as_view(exchange_filter=my_exchange_filter), name='write'),

function interface:
In:
    ``sender``: a User instance
    ``recipient``: a User instance
    ``recipients_list``: the full list of recipients or None
Out: None, False, '', 'a reason', or ValidationError

Auto-complete field
-------------------
Views supporting an auto-complete parameter are: ``WriteView``, ``ReplyView``.
Examples::
    ...View.as_view(autocomplete_channels=(None,'anonymous_ac')), name='write'),
    ...View.as_view(autocomplete_channels='write_ac'), name='write'),
    ...View.as_view(autocomplete_channel='reply_ac'), name='reply'),

Auto moderators
---------------
Views supporting an ``auto-moderators`` parameter are: ``WriteView``, ``ReplyView``.
Example::
    def mod1(message):
        # ...
        return None
    def mod2(message):
        # ...
        return None
    mod2.default_reason = 'mod2 default reason'
    ...
    ...View.as_view(auto_moderators=(mod1, mod2)), name='write'),
    ...View.as_view(auto_moderators=mod1), name='reply'),

function interface:
In: ``message``: a Message instance
Out: rating or (rating, "reason")
    with reting: None, 0 or False, 100 or True, 1..99

Others
------
Refer to documentation.
    ...View.as_view(form_classes=(MyCustomWriteForm, MyCustomAnonymousWriteForm)), name='write'),
    ...View.as_view(form_class=MyCustomFullReplyForm), name='reply'),
    ...View.as_view(form_class=MyCustomQuickReplyForm), name='view'),
    ...View.as_view(template_name='my_custom_view.html'), name='view'),
    ...View.as_view(success_url='postman:inbox'), name='reply'),
    ...View.as_view(formatters=(format_subject, format_body)), name='reply'),
    ...View.as_view(formatters=(format_subject, format_body)), name='view'),

"""
from __future__ import unicode_literals

try:
    from django.conf.urls import patterns, url  # django 1.4
except ImportError:
    from django.conf.urls.defaults import patterns, url  # django 1.3
from django.views.generic.base import RedirectView

from . import OPTIONS
from . import views
from .views import (InboxView, SentView, ArchivesView, TrashView,
        WriteView, ReplyView, MessageView, ConversationView,
        ArchiveView, DeleteView, UndeleteView)


urlpatterns = patterns('',
    url(r'^inbox/(?:(?P<option>'+OPTIONS+')/)?$', InboxView.as_view(), name='inbox'),
    url(r'^sent/(?:(?P<option>'+OPTIONS+')/)?$', SentView.as_view(), name='sent'),
    url(r'^archives/(?:(?P<option>'+OPTIONS+')/)?$', ArchivesView.as_view(), name='archives'),
    url(r'^trash/(?:(?P<option>'+OPTIONS+')/)?$', TrashView.as_view(), name='trash'),
    url(r'^write/(?:(?P<recipients>[^/#]+)/)?$', WriteView.as_view(), name='write'),
    url(r'^reply/(?P<message_id>[\d]+)/$', ReplyView.as_view(), name='reply'),
    url(r'^view/(?P<message_id>[\d]+)/$', MessageView.as_view(), name='view'),
    url(r'^view/t/(?P<thread_id>[\d]+)/$', ConversationView.as_view(), name='view_conversation'),
    url(r'^archive/$', ArchiveView.as_view(), name='archive'),
    url(r'^delete/$', DeleteView.as_view(), name='delete'),
    url(r'^undelete/$', UndeleteView.as_view(), name='undelete'),
    url(r'^encrypt/$', views.encrypt, name='encrypt'),
    url(r'^decrypt/$', views.decrypt, name='decrypt'),
    (r'^$', RedirectView.as_view(url='inbox/', permanent=True)),
)

postman/views.py
from __future__ import unicode_literals

from django import VERSION
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
try:
    from django.contrib.auth import get_user_model  # Django 1.5
except ImportError:
    from postman.future_1_5 import get_user_model
try:
    from django.contrib.sites.shortcuts import get_current_site  # Django 1.7
except ImportError:
    from django.contrib.sites.models import get_current_site
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect
from django.utils.decorators import method_decorator
from django.utils.encoding import force_text
try:
    from django.utils.six.moves.urllib.parse import urlsplit, urlunsplit  # Django 1.4.11, 1.5.5
except ImportError:
    from urlparse import urlsplit, urlunsplit
try:
    from django.utils.timezone import now  # Django 1.4 aware datetimes
except ImportError:
    from datetime import datetime
    now = datetime.now
from django.utils.translation import ugettext as _, ugettext_lazy
from django.views.decorators.csrf import csrf_protect
from django.views.generic import FormView, TemplateView, View

from . import OPTION_MESSAGES
from .fields import autocompleter_app
from .forms import WriteForm, AnonymousWriteForm, QuickReplyForm, FullReplyForm
from .models import Message, get_order_by
from .utils import format_subject, format_body

login_required_m = method_decorator(login_required)
csrf_protect_m = method_decorator(csrf_protect)


##########
# Helpers
##########
def _get_referer(request):
    """Return the HTTP_REFERER, if existing."""
    if 'HTTP_REFERER' in request.META:
        sr = urlsplit(request.META['HTTP_REFERER'])
        return urlunsplit(('', '', sr.path, sr.query, sr.fragment))


########
# Views
########
class NamespaceMixin(object):
    """Common code to manage the namespace."""

    def render_to_response(self, context, **response_kwargs):
        if VERSION >= (1, 8):
            self.request.current_app = self.request.resolver_match.namespace
        else:
            response_kwargs['current_app'] = self.request.resolver_match.namespace
        return super(NamespaceMixin, self).render_to_response(context, **response_kwargs)


class FolderMixin(NamespaceMixin, object):
    """Code common to the folders."""
    http_method_names = ['get']

    @login_required_m
    def dispatch(self, *args, **kwargs):
        return super(FolderMixin, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(FolderMixin, self).get_context_data(**kwargs)
        params = {}
        option = kwargs.get('option')
        if option:
            params['option'] = option
        order_by = get_order_by(self.request.GET)
        if order_by:
            params['order_by'] = order_by
        msgs = getattr(Message.objects, self.folder_name)(self.request.user, **params)
        viewname = 'postman:' + self.view_name
        current_instance = self.request.resolver_match.namespace
        context.update({
            'pm_messages': msgs,  # avoid 'messages', already used by contrib.messages
            'by_conversation': option is None,
            'by_message': option == OPTION_MESSAGES,
            'by_conversation_url': reverse(viewname, current_app=current_instance),
            'by_message_url': reverse(viewname, args=[OPTION_MESSAGES], current_app=current_instance),
            'current_url': self.request.get_full_path(),
            'gets': self.request.GET,  # useful to postman_order_by template tag
        })
        return context


class InboxView(FolderMixin, TemplateView):
    """
    Display the list of received messages for the current user.

    Optional URLconf name-based argument:
        ``option``: display option:
            OPTION_MESSAGES to view all messages
            default to None to view only the last message for each conversation
    Optional URLconf configuration attribute:
        ``template_name``: the name of the template to use

    """
    # for FolderMixin:
    folder_name = 'inbox'
    view_name = 'inbox'
    # for TemplateView:
    template_name = 'postman/inbox.html'


class SentView(FolderMixin, TemplateView):
    """
    Display the list of sent messages for the current user.

    Optional arguments and attributes: refer to InboxView.

    """
    # for FolderMixin:
    folder_name = 'sent'
    view_name = 'sent'
    # for TemplateView:
    template_name = 'postman/sent.html'


class ArchivesView(FolderMixin, TemplateView):
    """
    Display the list of archived messages for the current user.

    Optional arguments and attributes: refer to InboxView.

    """
    # for FolderMixin:
    folder_name = 'archives'
    view_name = 'archives'
    # for TemplateView:
    template_name = 'postman/archives.html'


class TrashView(FolderMixin, TemplateView):
    """
    Display the list of deleted messages for the current user.

    Optional arguments and attributes: refer to InboxView.

    """
    # for FolderMixin:
    folder_name = 'trash'
    view_name = 'trash'
    # for TemplateView:
    template_name = 'postman/trash.html'


class ComposeMixin(NamespaceMixin, object):
    """
    Code common to the write and reply views.

    Optional attributes:
        ``success_url``: where to redirect to after a successful POST
        ``user_filter``: a filter for recipients
        ``exchange_filter``: a filter for exchanges between a sender and a recipient
        ``max``: an upper limit for the recipients number
        ``auto_moderators``: a list of auto-moderation functions

    """
    http_method_names = ['get', 'post']
    success_url = None
    user_filter = None
    exchange_filter = None
    max = None
    auto_moderators = []

    def get_form_kwargs(self):
        kwargs = super(ComposeMixin, self).get_form_kwargs()
        if self.request.method == 'POST':
            kwargs.update({
                'sender': self.request.user,
                'user_filter': self.user_filter,
                'exchange_filter': self.exchange_filter,
                'max': self.max,
                'site': get_current_site(self.request),
            })
        return kwargs

    def get_success_url(self):
        return self.request.GET.get('next') or self.success_url or _get_referer(self.request) or 'postman:inbox'

    def form_valid(self, form):
        params = {'auto_moderators': self.auto_moderators}
        if hasattr(self, 'parent'):  # only in the ReplyView case
            params['parent'] = self.parent
        is_successful = form.save(**params)
        if is_successful:
            messages.success(self.request, _("Message successfully sent."), fail_silently=True)
        else:
            messages.warning(self.request, _("Message rejected for at least one recipient."), fail_silently=True)
        return redirect(self.get_success_url())

    def get_context_data(self, **kwargs):
        context = super(ComposeMixin, self).get_context_data(**kwargs)
        context.update({
            'autocompleter_app': autocompleter_app,
            'next_url': self.request.GET.get('next') or _get_referer(self.request),
        })
        return context


class WriteView(ComposeMixin, FormView):
    """
    Display a form to compose a message.

    Optional URLconf name-based argument:
        ``recipients``: a colon-separated list of usernames
    Optional attributes:
        ``form_classes``: a 2-tuple of form classes
        ``autocomplete_channels``: a channel name or a 2-tuple of names
        ``template_name``: the name of the template to use
        + those of ComposeMixin

    """
    form_classes = (WriteForm, AnonymousWriteForm)
    autocomplete_channels = None
    template_name = 'postman/write.html'

    @csrf_protect_m
    def dispatch(self, *args, **kwargs):
        if getattr(settings, 'POSTMAN_DISALLOW_ANONYMOUS', False):
            return login_required(super(WriteView, self).dispatch)(*args, **kwargs)
        return super(WriteView, self).dispatch(*args, **kwargs)

    def get_form_class(self):
        return self.form_classes[0] if self.request.user.is_authenticated() else self.form_classes[1]

    def get_initial(self):
        initial = super(WriteView, self).get_initial()
        if self.request.method == 'GET':
            initial.update(self.request.GET.items())  # allow optional initializations by query string
            recipients = self.kwargs.get('recipients')
            if recipients:
                # order_by() is not mandatory, but: a) it doesn't hurt; b) it eases the test suite
                # and anyway the original ordering cannot be respected.
                user_model = get_user_model()
                name_user_as = getattr(settings, 'POSTMAN_NAME_USER_AS', user_model.USERNAME_FIELD)
                usernames = list(user_model.objects.values_list(name_user_as, flat=True).filter(
                    is_active=True,
                    **{'{0}__in'.format(name_user_as): [r.strip() for r in recipients.split(':') if r and not r.isspace()]}
                ).order_by(name_user_as))
                if usernames:
                    initial['recipients'] = ', '.join(map(force_text, usernames))
        return initial

    def get_form_kwargs(self):
        kwargs = super(WriteView, self).get_form_kwargs()
        if isinstance(self.autocomplete_channels, tuple) and len(self.autocomplete_channels) == 2:
            channel = self.autocomplete_channels[self.request.user.is_anonymous()]
        else:
            channel = self.autocomplete_channels
        kwargs['channel'] = channel
        return kwargs


class ReplyView(ComposeMixin, FormView):
    """
    Display a form to compose a reply.

    Optional attributes:
        ``form_class``: the form class to use
        ``formatters``: a 2-tuple of functions to prefill the subject and body fields

postman/templates/autocomplete_postman_multiple_as1-1.html
{% extends "autocomplete.html" %}{% comment %}
This is a custom template for django-ajax-selects version 1.1.4/5 (not for 1.2+).
Channel:		postman_multiple_as1-1
Form Field:		AutoCompleteField
Usage:			Entering of multiple values.

There is no such template provided in the django-ajax-selects application.
Differences with the default template:
- it uses the "multiple: true" option of the jquery-plugin-autocomplete
- it fixes the issue http://code.google.com/p/django-ajax-selects/issues/detail?id=57
Note: this template is also used in the test suite.

{% endcomment %}
{% block script %}
	$('#{{ html_id }}').autocomplete('{{ lookup_url }}', {
		width: 320,
		formatItem: function(row) { return row[1]; },
		formatResult: function(row) { return row[2]; },
		multiple: true,
		dataType: "text"
	})
	$('#{{ html_id }}').result(function(event, data, formatted) {
		$('#{{ html_id }}').trigger("added");
	})
{% block extra_script %}{% endblock %}
{% endblock %}

postman/templates/autocomplete_postman_multiple_as1-2.html
{% extends "autocomplete.html" %}{% comment %}
This is a custom template for django-ajax-selects version 1.2+ (not for 1.1.4/5).
Channel:		postman_multiple_as1-2
Form Field:		AutoCompleteField
Usage:			Entering of multiple values.

There is no such template provided in the django-ajax-selects application.

{% endcomment %}
{% block script %}
	addAutoComplete("{{html_id}}", function(html_id) {
		function split(val) {
			return val.split(/,\s*/);
		}
		function extractLast(term) {
			return split(term).pop();
		}

		$("#"+html_id)
		// don't navigate away from the field on tab when selecting an item
		.bind("keydown", function(event) {
			if (event.keyCode === $.ui.keyCode.TAB &&
					$(this).data("autocomplete").menu.active) {
				event.preventDefault();
			}
		})
		.autocomplete({
			source: function(request, response) {
				$.getJSON("{{lookup_url}}", {
					term: extractLast(request.term)
				}, response);
			},
			search: function() {
				// custom minLength
				var term = extractLast(this.value);
				if (term.length < {{min_length}}) {
					return false;
				}
			},
			focus: function() {
				// prevent value inserted on focus
				return false;
			},
			select: function(event, ui) {
				var terms = split(this.value);
				// remove the current input
				terms.pop();
				// add the selected item
				terms.push(ui.item.value);
				// add placeholder to get the comma-and-space at the end
				terms.push("");
				this.value = terms.join(", ");
				$(this).trigger("added");
				return false;
			}
		}).autocompletehtml();
	});
{% block extra_script %}{% endblock %}
{% endblock %}

postman/templates/autocomplete_postman_multiple_as1-3.html
{% comment %}
This is a custom template for django-ajax-selects version 1.3+ (not for 1.2.x).
Channel:		postman_multiple_as1-3
Form Field:		AutoCompleteField
Usage:			Entering of multiple values.

There is no such template provided in the django-ajax-selects application.

This templage could almost {% extends "autocomplete.html" %}
 and our field would be first processed as an ordinary "autocomplete" by ajax_select.js.
 An autocomplete("option", opts) in the extra_script block would provide only the additions & overrides.
Alas, we need to register our keydown handler before the one set by autocomplete(),
 otherwise there will be no longer a menu.active at runtime.
So data-ajax-select has any other value - the contents doesn't matter.
{% endcomment %}
<input type="text" name="{{name}}" id="{{html_id}}" value="{{current_repr}}" autocomplete="off" data-ajax-select="autocomplete-postman" data-plugin-options="{{ data_plugin_options }}" {{ extra_attrs }} />
<script type="text/javascript">
(function ($) {
  $(document).ready(function(){
    {# can't call addAutoComplete() here, available only in the scope of ajax_select.js inner function #}
    var $inp = $("#{{html_id}}"),
      opts = JSON.parse($inp.attr('data-plugin-options'));

    {# derived from http://jqueryui.com/resources/demos/autocomplete/multiple-remote.html #}
    function split(val) {
      return val.split(/,\s*/);
    }
    function extractLast(term) {
      return split(term).pop();
    }
    $inp.bind("keydown", function(event) {
      {# don't navigate away from the field on tab when selecting an item #}
      if (event.keyCode === $.ui.keyCode.TAB &&
          $(this).data("ui-autocomplete").menu.active) {  {# autocomplete("instance") is 1.11, not 1.10 of v1.3.6 #}
        event.preventDefault();
      }
    });
    var option_source = opts.source;
    opts.source = function(request, response) {
        $.getJSON(option_source, {
          term: extractLast(request.term)
        }, response);
      };
    opts.search = function() {
        {# custom minLength #}
        var term = extractLast(this.value);
        if (term.length < {{min_length}}) {
          return false;
        }
      };
    opts.focus = function() {
        {# prevent value inserted on focus #}
        return false;
      };
    opts.select = function(event, ui) {
        var terms = split(this.value);
        {# remove the current input #}
        terms.pop();
        {# add the selected item #}
        terms.push(ui.item.value);
        {# add placeholder to get the comma-and-space at the end #}
        terms.push("");
        this.value = terms.join(", ");
        $(this).trigger("added", [ui.item.pk, ui.item]);
        return false;
      };
    $inp.autocomplete(opts);
  });
})(window.jQuery);
</script>
{% block help %}{% if help_text %}<p class="help">{{ help_text }}</p>{% endif %}{% endblock %}

postman/templates/autocomplete_postman_single_as1-1.html
{% extends "autocomplete.html" %}{% comment %}
This is a custom template for django-ajax-selects version 1.1.4/5 (not for 1.2+).
Channel:		postman_single_as1-1
Form Field:		AutoCompleteField
Usage:			Basic entering of a single value.

It is the same as the default template, except that it fixes the issue:
http://code.google.com/p/django-ajax-selects/issues/detail?id=57
Note: this template is also used in the test suite.

{% endcomment %}
{% block script %}
	$('#{{ html_id }}').autocomplete('{{ lookup_url }}', {
		width: 320,
		formatItem: function(row) { return row[1]; },
		formatResult: function(row) { return row[2]; },
		dataType: "text"
	})
	$('#{{ html_id }}').result(function(event, data, formatted) {
		$('#{{ html_id }}').trigger("added");
	})
{% block extra_script %}{% endblock %}
{% endblock %}

postman/templates/base.html
<!DOCTYPE html>

<html>

<head>
    {% load postman_tags %}

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.3.5/darkly/bootstrap.min.css" crossorigin="anonymous">
  


  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

{% block extrahead %}
{% endblock %}
<title> Base test 1 </title>
<link type="text/css" media="all" rel="stylesheet" href="
{# dj v1.4 #}{% load static %}{% static 'postman/css/postman.css' %}
{# dj v1.3 #}{# {{ STATIC_URL }}postman/css/postman.css #}
{# dj v1.2 #}{# {{ MEDIA_URL }}postman/css/postman.css #}
" />

</head>

<body>

  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">SecureShare</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class><a href="/mainpage">Home</a></li>
        <li><a href="/mainpage/myReports">My Reports</a></li>
        <li><a href="/mainpage/publicReports">Public Reports</a></li>
        <li><a href="/mainpage/myGroups">My Groups</a></li>

          <li><a href="/messages/">Messages{% postman_unread as unread_count %} {% if unread_count %} <span class="badge">{{ unread_count }}{% endif %} </span></a><li>
        <li><a href="/mainpage/profile">User profile </a></li>
        {% if request.user.is_staff %}
        <li><a class="btn btn-md btn-primary" href="/siteadmin/"> Site Admin </a></li>
        {% endif %}
        <li><a href="/mainpage/logout">Logout</a><li>
      </ul>
     
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Github link</a></li>
      </ul>
    </div>
  </div>
</nav>
<div class="container">
<div class="row">
	<div class="col-md-8">
{% block postman_menu %}
{% endblock %}

<pre>
<a href="{% url 'postman:encrypt' %}"> Encrypt Your Message </a>
<a href="{% url 'postman:decrypt' %}"> Decrypt Your Message </a>

</pre>
 <!--<li><a href="{% url 'postman:inbox' %}">"Inbox" </a></li>
 <li><a href="{% url 'postman:sent' %}">"Sent Messages"</a></li>
 <li><a href="{% url 'postman:write' %}">"Write"</a></li>
 <li><a href="{% url 'postman:archives' %}"> "Archives"</a></li>
 <li><a href="{% url 'postman:trash' %}"> "Trash"</a></li>

-->

{% block content %}
{% endblock %}

</div>
</div>
</div>

</body>

</html>

postman/templates/decrypt.html
<!DOCTYPE html>
<html>
<form id = "enc_form" action="/messages/decrypt/" enctype="multipart/form-data" method="post">
    {% csrf_token %}
    <label for="msg">Your message: </label>
    <textarea cols="40" rows="5" name = "msg"  value="{{ message }}"></textarea>
    <label for="key">Your key: </label>
    <textarea cols="40" rows="5" name = "key"  value="{{ message }}"></textarea>
    <input type="submit" name="Submit">
</form>
{% if dec %}
        Decrypted Message: <input type="text" name="FirstName" value="{{dec_msg}}"><br>
{% endif %}
</html>

postman/templates/encrypt.html
<!DOCTYPE html>
<html>
<form id = "enc_form" action="/messages/encrypt/" enctype="multipart/form-data" method="post">
	{% csrf_token %}
    <label for="msg">Your message: </label>
    <textarea cols="40" rows="5" name = "msg"  value="{{ message }}"></textarea>
    <input type="submit" name="Submit">
</form>
{% if enc %}
        Encrypted Message: <input type="text" name="FirstName" value="{{enc_msg}}"><br>
        Key: <input type="text" name="Key" value="{{key}}"><br>
{% endif %}

<a href="{% url 'postman:write' %}"> Copy the encrypted message and send it here </a>
</html>