cs3240_f15_team14/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^mainpage/', include('mainpage.urls')),
    url(r'^myapplication/', include('myapplication.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^uploader/',include('uploader.urls')),
    url(r'^siteadmin/', include('siteadmin.urls')),
    url(r'^messages/', include('postman.urls', namespace='postman', app_name='postman')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dev/cs3240_f15_team14/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^myapplication/', include('myapplication.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^uploader/',include('uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

postman/urls.py
"""
If the default usage of the views suits you, simply use a line like
this one in your root URLconf to set up the default URLs::

    (r'^messages/', include('postman.urls', namespace='postman', app_name='postman')),

Otherwise you may customize the behavior by passing extra parameters.

Recipients Max
--------------
Views supporting the parameter are: ``WriteView``, ``ReplyView``.
Example::
    ...View.as_view(max=3), name='write'),
See also the ``POSTMAN_DISALLOW_MULTIRECIPIENTS`` setting

User filter
-----------
Views supporting a user filter are: ``WriteView``, ``ReplyView``.
Example::
    def my_user_filter(user):
        if user.get_profile().is_absent:
            return "is away"
        return None
    ...
    ...View.as_view(user_filter=my_user_filter), name='write'),

function interface:
In: a User instance
Out: None, False, '', 'a reason', or ValidationError

Exchange filter
---------------
Views supporting an exchange filter are: ``WriteView``, ``ReplyView``.
Example::
    def my_exchange_filter(sender, recipient, recipients_list):
        if recipient.relationships.exists(sender, RelationshipStatus.objects.blocking()):
            return "has blacklisted you"
        return None
    ...
    ...View.as_view(exchange_filter=my_exchange_filter), name='write'),

function interface:
In:
    ``sender``: a User instance
    ``recipient``: a User instance
    ``recipients_list``: the full list of recipients or None
Out: None, False, '', 'a reason', or ValidationError

Auto-complete field
-------------------
Views supporting an auto-complete parameter are: ``WriteView``, ``ReplyView``.
Examples::
    ...View.as_view(autocomplete_channels=(None,'anonymous_ac')), name='write'),
    ...View.as_view(autocomplete_channels='write_ac'), name='write'),
    ...View.as_view(autocomplete_channel='reply_ac'), name='reply'),

Auto moderators
---------------
Views supporting an ``auto-moderators`` parameter are: ``WriteView``, ``ReplyView``.
Example::
    def mod1(message):
        # ...
        return None
    def mod2(message):
        # ...
        return None
    mod2.default_reason = 'mod2 default reason'
    ...
    ...View.as_view(auto_moderators=(mod1, mod2)), name='write'),
    ...View.as_view(auto_moderators=mod1), name='reply'),

function interface:
In: ``message``: a Message instance
Out: rating or (rating, "reason")
    with reting: None, 0 or False, 100 or True, 1..99

Others
------
Refer to documentation.
    ...View.as_view(form_classes=(MyCustomWriteForm, MyCustomAnonymousWriteForm)), name='write'),
    ...View.as_view(form_class=MyCustomFullReplyForm), name='reply'),
    ...View.as_view(form_class=MyCustomQuickReplyForm), name='view'),
    ...View.as_view(template_name='my_custom_view.html'), name='view'),
    ...View.as_view(success_url='postman:inbox'), name='reply'),
    ...View.as_view(formatters=(format_subject, format_body)), name='reply'),
    ...View.as_view(formatters=(format_subject, format_body)), name='view'),

"""
from __future__ import unicode_literals

try:
    from django.conf.urls import patterns, url  # django 1.4
except ImportError:
    from django.conf.urls.defaults import patterns, url  # django 1.3
from django.views.generic.base import RedirectView

from . import OPTIONS
from . import views
from .views import (InboxView, SentView, ArchivesView, TrashView,
        WriteView, ReplyView, MessageView, ConversationView,
        ArchiveView, DeleteView, UndeleteView)


urlpatterns = patterns('',
    url(r'^inbox/(?:(?P<option>'+OPTIONS+')/)?$', InboxView.as_view(), name='inbox'),
    url(r'^sent/(?:(?P<option>'+OPTIONS+')/)?$', SentView.as_view(), name='sent'),
    url(r'^archives/(?:(?P<option>'+OPTIONS+')/)?$', ArchivesView.as_view(), name='archives'),
    url(r'^trash/(?:(?P<option>'+OPTIONS+')/)?$', TrashView.as_view(), name='trash'),
    url(r'^write/(?:(?P<recipients>[^/#]+)/)?$', WriteView.as_view(), name='write'),
    url(r'^reply/(?P<message_id>[\d]+)/$', ReplyView.as_view(), name='reply'),
    url(r'^view/(?P<message_id>[\d]+)/$', MessageView.as_view(), name='view'),
    url(r'^view/t/(?P<thread_id>[\d]+)/$', ConversationView.as_view(), name='view_conversation'),
    url(r'^archive/$', ArchiveView.as_view(), name='archive'),
    url(r'^delete/$', DeleteView.as_view(), name='delete'),
    url(r'^undelete/$', UndeleteView.as_view(), name='undelete'),
    url(r'^encrypt/$', views.encrypt, name='encrypt'),
    url(r'^decrypt/$', views.decrypt, name='decrypt'),
    (r'^$', RedirectView.as_view(url='inbox/', permanent=True)),
)

siteadmin/urls.py
from django.conf.urls import url

from . import views 

urlpatterns = [
    url(r'^$', views.mainpage, name='mainpage'),
    url(r'^admins/$', views.admins, name='admins'),
    url(r'^admins/(?P<user_name>[a-z0-9]+)$', views.newadmin, name='newadmin'),
    url(r'^users/$', views.userlist, name='userlist'),
    url(r'^groups/$', views.groups, name='groups'),
    url(r'^groups/visualization/$', views.groupvis, name='groupvis'),

    url(r'^(?P<user_name>[a-z0-9]+)/$', views.userinfo, name='userinfo'),
    url(r'^(?P<user_name>[a-z0-9]+)/suspendaccount$', views.suspendaccount, name='suspendaccount'),
    url(r'^(?P<user_name>[a-z0-9]+)/unsuspendaccount$', views.unsuspendaccount, name='unsuspendaccount'),


]

siteadmin/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
import django


# Create your models here.


class admin(models.Model):
	permissions = models.ManyToManyField(User)

uploader/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.conf import settings
from vote.managers import VotableManager
from django.contrib.auth.models import User
import django

class Folder(models.Model):
	name = models.CharField(max_length=100)
	user = models.CharField(max_length=100, default="")
	def __str__(self):
		return self.name;

class Report(models.Model):
	timestamp = models.DateTimeField(auto_now_add=True)
	name = models.CharField(max_length=100)
	user = models.CharField(max_length=100, default="")
	sd = models.CharField(max_length=200)
	ld = models.CharField(max_length=1000)
	lat = models.FloatField(default=0)
	lon = models.FloatField(default=0)
	public = models.BooleanField(default=False)
	folder = models.ForeignKey(Folder, null=True, default=None, blank=True)
	votes = VotableManager()
	def __str__(self):
		return self.name;
	
class Document(models.Model):
	report = models.ForeignKey(Report, null=True)
	name = models.CharField(max_length=100, null=True, default=None, blank=True)
	encrypted = models.BooleanField(default=False)
	docfile = models.FileField(upload_to='documents')
	def __str__(self):
		return str(self.docfile);

class Group2(models.Model):
	name = models.CharField(max_length=100)
	creator = models.CharField(max_length=100, default="")
	permissions = models.ManyToManyField(User)
	reports = models.ManyToManyField(Report)
	def __str__(self):
		return str(self.name);

siteadmin/views.py
from django.shortcuts import render
from mainpage.search import get_query
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect
from django.template import RequestContext, loader
from django.http import HttpResponse
from uploader.models import Document, Report, Folder, Group2
from uploader.forms import DocumentForm, reportEditForm
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import logout
from uploader.forms import DocumentForm, reportEditForm, folderEditForm, groupEditForm
from siteadmin.models import admin
import pdb;

# Create your views here.

def mainpage(request):

	reports = Report.objects.all()

	if not request.user.is_staff:
		return HttpResponseRedirect('/mainpage/')
	return render_to_response(
		'siteadminmain.html',
		{'reports': reports},
		context_instance=RequestContext(request)
		)

def userlist(request):
	users = User.objects.all()
	reports = Report.objects.all()
	if not request.user.is_staff:
		return HttpResponseRedirect('/mainpage/')
	return render_to_response(
		'users.html',
		{'users': users, 'reports':reports},
		context_instance=RequestContext(request)
		)

def userinfo(request, user_name):
	users = User.objects.all()
	reports = Report.objects.all()
	groups = Group2.objects.all()
	documents = Document.objects.all()
	if not request.user.is_staff:
		return HttpResponseRedirect('/mainpage/')

	for user in users:
		if user.username == user_name:
			return render(request, 'siteadmin/userinfo.html', {'reports':reports, 'groups':groups, 'documents':documents, 'user_name':user_name, 'user':user})

	return HttpResponseRedirect('/siteadmin/')


def suspendaccount(request, user_name):
	users = User.objects.all()
	if not request.user.is_staff:
		return HttpResponseRedirect('/mainpage/')
	for user in users:
		if user.username == user_name:
			user.is_active = True
			user.save()
	return HttpResponseRedirect('/siteadmin/' + user_name)

def unsuspendaccount(request, user_name):
	users = User.objects.all()
	if not request.user.is_staff:
		return HttpResponseRedirect('/mainpage/')
	for user in users:
		if user.username == user_name:
			user.is_active = False
			user.save()
	return HttpResponseRedirect('/siteadmin/' + user_name)

def admins(request):
	users = User.objects.all()
	if not request.user.is_staff:
		return HttpResponseRedirect('/mainpage/')
	admins = admin.objects.all()
	return render(request, 
		'siteadmin/admins.html',
		{'users':users, 'admins': admins}
		)

def groups(request):
	if not request.user.is_staff:
		return HttpResponseRedirect('/mainpage/')
	groups = Group2.objects.all()
	return render_to_response(
        'groups.html',
        {'groups': groups},
        context_instance=RequestContext(request)
        )

def newadmin(request, user_name):
	if not request.user.is_staff:
		return HttpResponseRedirect('/mainpage/')
	users = User.objects.all()
	user_name_added = user_name
	groups = Group2.objects.all()
	for user in users:
		if user.username == user_name:
			user.is_staff = True
			user.save()
	return render(request, 'siteadmin/admins.html',
		{'groups':groups, 'users':users}
		)

def groupvis(request):
	groups = Group2.objects.all()
	users = User.objects.all()

	return render_to_response(
		'visualization.html',
		{'groups':groups, 'users':users},
		context_instance=RequestContext(request)
		)

siteadmin/templates/siteadmin/admins.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.3.5/flatly/bootstrap.min.css" crossorigin="anonymous">
	</head>

	<body>
		<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">SecureWitness</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/siteadmin">Home</a></li>
        <li><a href="/siteadmin/users"> User List </a></li>
        <li class="active"><a href="/siteadmin/admin">Admins<span class="sr-only">(current)</span></a></li>
        <li><a href="/siteadmin/groups">Groups</a><li>
        <li><a href="/mainpage/logout">Logout</a><li>


      </ul>
     
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Github link</a></li>
      </ul>
    </div>
  </div>
</nav>
 
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
		<!-- List of uploaded documents -->
		
		<div class="container">
			<h1> Add a new admin </h1>
		</div>
		{% if users %}
			<ul>
			{% for user in users %}
				{% if not user.is_staff %}
        <div class="container">
			<div class="row">
      <div class="col-lg-6">
        <div class="well">
          

				<h3> {{ user.username }} </h3><a class="btn btn-info btn-lg" href="/siteadmin/admins/{{user.username}}"> Add </a></br >
      </br>
    </br>

      	</div>
    </div>
    {% endif %}
      {% endfor %}
    </ul>
     </div>
  </div>


		{% else %}
			<p>No users.</p>
		{% endif %}

	</body>
</html>

siteadmin/templates/siteadmin/userinfo.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
        <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>

    	<meta http-equiv="X-UA-Compatible" content="IE=edge">
    	<meta name="viewport" content="width=device-width, initial-scale=1">
    	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">

   	 	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.3.5/flatly/bootstrap.min.css" crossorigin="anonymous">
	</head>

	<body>
		<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">SecureWitness</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/siteadmin">Home</a></li>
        <li><a href="/siteadmin/users">User List</a></li>
        <li class="active"><a href="/siteadmin/admins">Admins</a></li>
        <li><a href="/mainpage/logout">Logout</a><li>


      </ul>
     
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Github link</a></li>
      </ul>
    </div>
  </div>
</nav>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
		<!-- Upload form. Note enctype attribute! -->
<h1> User: {{user_name }} {% if not user.is_active %} (This account is suspended) {% endif %} </h1>
{% if reports %} 
  
  
  {% if not user.is_active %}
  <form action="{% url "suspendaccount" user_name %}" method="post">
      {% csrf_token %}
      <input type="hidden" name="idofreport" value="{{ idofreport }}">
      
      <p><input class="btn btn-success btn-lg" type="submit" value="Unsuspend user" /></p>
    </form>

    {% else %}
<form action="{% url "unsuspendaccount" user_name %}" method="post">
      {% csrf_token %}
      <input type="hidden" name="idofreport" value="{{ idofreport }}">
      
      <p><input class="btn btn-warning btn-lg" type="submit" value="Suspend user" /></p>
    </form>

    {% endif %}

   <ul>
     {% for report in reports %}
     
     {% if report.user == user_name %}
     <div class="row">
      <div class="col-lg-8">
        <div class="bs-component">
          <div class="panel panel-primary">
           <div class="panel-heading"> 
        Report Title: {{ report.name }} 
        &nbsp;
        &nbsp;
        <form action="{% url "deletereport" %}" method="post" enctype="multipart/form-data" style="display: inline;">
        {% csrf_token %}
        <input type="hidden" name="idofreport" value="{{ report.id }}">
        <input class="btn btn-danger btn-sm" type="submit" value="Delete"> 
        </form>
      </div>
      <div class="panel-body">
        
        </br>
        Folder: {{ report.folder }} </br >
        Date created: {{ report.timestamp }} </br >
        Short Description: {{ report.sd }} </br >
        Documents </br >
        {% for document in report.document_set.all %}
          <ul><a href="{{ document.docfile.url }}">{{ document.docfile.name }}</a></ul>

        {% endfor %}

        </br >
      </div>
    </div>
  </div>
</div>
</div>
    {% endif %}
        
     {% endfor %}

</ul>

{% else %}
   <p> SiteAdmin is having soem problems. </p>

{% endif %}

		
	</body>

</html> 